version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contacts_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/contacts_db
      PORT: 3000
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: ['sh', '-c', 'npm run dev']

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '5173:4173'
    depends_on:
      - backend

volumes:
  db_data:
